name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - uses: actions/checkout@v3
      - name: Build project
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
     
      - uses: actions/upload-artifact@v4.3.1
      - name: Upload a Build Artifact
        with:
          # Artifact name
          name: Artifact2
        
